### ISSUE TITLE
No artwork with deadbeef 1.9.1

### ISSUE THREAD

**Issue by kuon** [DeaDBeeF-Player/deadbeef-mpris2-plugin#2]
I just update to deadbeef 1.9.1 with mpris plugin  1.14 and I lost the artwork URL in the metadata. Artwork plugin is now 2.0.

I think this is fixed by https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin/pull/1 but having the issue might help other people looking for a solution.

**Comment by Oleksiy-Yakovenko** [comment]
I just merged the PR which updates the code to use the new artwork plugin.
