### ISSUE TITLE
logging does not appear to work

### ISSUE THREAD

**Issue by cmm** [DeaDBeeF-Player/deadbeef-mpris2-plugin#3]
"Enable logging" is checked in the GUI, MPRIS events are sent, but no MPRIS logs are seen either in the log window or in the journal

**Comment by cmm** [comment]
might have something to do with the fact that the property being checked is "vfs_curl.trace" and not "mpris.trace", but fixing that is somehow not enough

**Comment by Oleksiy-Yakovenko** [comment]
Fixed and tested, it works now :)
