### ISSUE TITLE
DeaDBeeF WARNING: plugin "MPRISv2 plugin" wants API v1.18 (got 1.17), will not be loaded

### ISSUE THREAD

**Issue by vfedyay** [DeaDBeeF-Player/deadbeef-mpris2-plugin#8]
Not sure it is an issue for mpris2-plugin or DeaDBeeF itself.
Successfully compiled mpris2-plugin on Debian 12 - all needed header files took in DeaDBeeF repo.
But have this warning starting DeaDBeeF:

WARNING: plugin "MPRISv2 plugin" wants API v1.18 (got 1.17), will not be loaded
starting deadbeef 1.9.6 [static] [portable]
...
loading plugin /home/wowik/deadbeef-1.9.6/plugins/mpris.so
plugin mpris not found or failed to load

**Comment by misscx** [comment]
遇到同样的问题，应该是插件没升级，与最新的deadbeef不兼容导致的吧？

**Comment by misscx** [comment]
I have found a solution to the problem by modifying line 188 of scr/mpris. c as follows:

.plugin.api_vmajor = DB_API_VERSION_MAJOR,\
.plugin.api_vminor = DB_API_VERSION_MAJOR, 
.plugin.type = DB_PLUGIN_MISC,

![截图 2024-05-12 22-11-53](https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin/assets/5102639/f9b7e655-00b2-4c94-a390-82169b6e3f75)
